apiVersion: v1
kind: ConfigMap
metadata:
  name: convoy-config
  labels:
    app.kubernetes.io/name: {{ include "convoy.name" . }}
    helm.sh/chart: {{ include "convoy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  convoy.json: {{ toJson .Values.config | quote }}
