apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "convoy-indexer.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "convoy-indexer.name" . }}
    helm.sh/chart: {{ include "convoy-indexer.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "convoy-indexer.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        updatedAt: {{ now | quote }}
      labels:
        app.kubernetes.io/name: {{ include "convoy-indexer.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
        - name: convoy-config
          configMap:
            name: convoy-config
            items: 
              - key: convoy.json
                path: convoy.json
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          volumeMounts:
            - name: convoy-config
              mountPath: /config
          command: ["/cmd"]
          args: ["index", "--config", "/config/convoy.json"]
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
              protocol: TCP
          env:
            - name: SERVICE_NAME
              value: "{{ .Chart.Name }}"
            - name: PORT
              value: {{ .Values.app.port | quote }}
            {{- range $env := .Values.app.env }}
            - name: {{ $env | upper }}
              valueFrom:
                secretKeyRef:
                  name: convoy
                  key: {{ $env }}
            {{- end }}
          livenessProbe:
            exec:
              command: 
              - ls -la
            initialDelaySeconds: 30
          readinessProbe:
            exec:
              command: 
              - ls -la
            initialDelaySeconds: 30
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}