apiVersion: v2
name: convoy
description: Open Source Webhooks Gateway

type: application


version: "v1.0.0"

appVersion: "0.9.2"



keywords:
  - Webhooks
  - Kubernetes
  - Convoy
maintainers:
  - name: Convoy Engineering Team
    email: engineering@getconvoy.io
    url: https://getconvoy.io

  - name: Obinna Odirionye
    email: odirionye@gmail.com
    url: https://iamobinna.com
