apiVersion: v2
name: convoy
description: Open Source Webhooks Gateway

type: application


version: "1.0.0"

appVersion: "0.9.2"



keywords:
  - Webhooks
  - Kubernetes
  - Convoy
maintainers:
  - name: Convoy Engineering Team
    email: engineering@getconvoy.io
    url: https://getconvoy.io

  - name: Obinna Odirionye
    email: odirionye@gmail.com
    url: https://iamobinna.com

dependencies:
  - name: postgresql
    version: 12.2.7
    repository: https://charts.bitnami.com/bitnami

  - name: redis
    version: 17.9.3
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled

