config:
  {
    "host": "http://localhost",
    "database": {
      "type": "postgres",
      "dsn": "postgres://postgres:postgres@postgresql/convoy?sslmode=disable"
    },
    "cache": {
      "type": "redis",
      "redis": {
        "dsn": "redis://redis-master:6379"
      }
    },
    "queue": {
      "type": "redis",
      "redis": {
        "dsn": "redis://redis-master:6379"
      }
    },
    "smtp": {
      "provider": "sendgrid",
      "url": "smtp.sendgrid.net",
      "port": 2525,
      "username": "username",
      "password": "password",
      "from": "e@mail.com"
    },
    "disable_endpoint": false,
    "auth": {
      "native": {
        "enabled": true
      },
      "jwt": {
        "enabled": true
      }
    }
  }

postgresql:
  enabled: true
  fullnameOverride: "postgresql"
  global:
    postgresql:
      auth:
        postgresPassword: "postgres"
        database: "convoy"
        password: "postgres"
        username: "postgres"

redis:
  architecture: standalone
  fullnameOverride: "redis"
  auth:
    enabled: false


worker:
  image:
    # -- Repository to be used by the worker. Latest tag is used by default
    repository: docker.cloudsmith.io/convoy/convoy/frain-dev/convoy
    # -- Pull policy for the worker image
    pullPolicy: IfNotPresent
    # -- Tag for the worker image
    tag: ""

  ingress:
    # -- Enable ingress for the worker
    enabled: false

  service:
    # -- Type of service for the worker
    type: ClusterIP
    # -- Port for the worker service
    port: 80

  autoscaling:
    # -- Enable autoscaling for the worker
    enabled: false
#    minReplicas: 1
#    maxReplicas: 10
#    targetCPUUtilizationPercentage: 80
#    targetMemoryUtilizationPercentage: 80





