global:
  convoy:
    # -- Docker image tags for all convoy services
    image: &image "docker.cloudsmith.io/convoy/convoy/frain-dev/convoy"

    # -- Docker image tags for all convoy services
    tag: &tag "v23.06.2"

    # -- Logger Level for all convoy services
    log_level: &logLevel "error"

    # -- Tracing config for all convoy services
    tracer_enabled: &tracerEnabled false
    # -- Tracing provider type
    tracer_type: &tracerType ""
    # -- NewRelic application name
    tracer_app_name: &tracerAppName ""
    # -- NewRelic tracing config enabled
    tracer_config_enabled: &tracerConfigEnabled true
    # -- NewRelic distributed tracing config enabled
    tracer_distributed_tracer_enabled: &tracerDistributedTracingEnabled true
    # -- NewRelic license key
    tracer_license_key: &tracerLicenseKey ""

  externalDatabase:
    # -- Enable external database, This will use postgresql chart, Change values if you use an external database
    enabled: &postgresEnabled true
    # -- Host for the external database
    host: "postgresql"
    # -- Password for the external database
    postgresPassword: &postgresPassword "postgres"
    # -- Database name for the external database
    database: &postgresDatabase "convoy"
    # -- Username for the external database
    password: &userPassword "postgres"
    # -- Username for the external database
    username: &username "postgres"
    # -- scheme for the external database. This is postgres by default
    scheme: "postgres"
    # -- Query params for the external database
    options: &options "sslmode=disable&connect_timeout=30"
    # -- Port for the external database
    port: 5432
    # -- secret name for username and password. assumes secret contains keys: "CONVOY_DB_USERNAME", "CONVOY_DB_PASSWORD"
    secret:
      enabled: false
      name: convoy

  nativeRedis:
    # -- Enable redis, This will use redis chart, Disable if you use an external redis
    enabled: &redisEnabled true
    # -- Host for the redis
    host: "redis-master"
    # -- password for the redis.
    password: &redisPassword "convoy"
    # -- Port for the redis
    port: 6379

  externalRedis:
    # -- Enable external redis, Enable this if you use an external redis and disable Native redis
    enabled: false
    # -- Host for the external redis
    host: ""
    # -- scheme for the external redis. This can be redis, rediss, redis-socket or redis-sentinel
    scheme: ""
    # -- username for the external redis.
    username: ""
    # -- password for the external redis.
    password: ""
    # -- Database name for the external redis.
    database: ""
    # -- Port for the external redis
    port: ""
    # -- secret name for username and password. assumes secret contains keys: "CONVOY_REDIS_USERNAME", "CONVOY_REDIS_PASSWORD"
    secret:
      enabled: false
      name: convoy

# @ignored
postgresql:
  enabled: *postgresEnabled
  fullnameOverride: "postgresql"
  global:
    postgresql:
      auth:
        postgresPassword: *postgresPassword
        username: *username
        password: *userPassword
        database: *postgresDatabase


# @ignored
redis:
  architecture: standalone
  fullnameOverride: "redis"
  auth:
    enabled: *redisEnabled
    password: *redisPassword


worker:
  # @ignored
  image:
    # -- Repository to be used by the worker. Latest tag is used by default
    repository: *image
    # -- Pull policy for the worker image
    pullPolicy: IfNotPresent
    # @ignored
    tag: *tag

  env:
    proxy: ""
    # @ignored
    log_level: *logLevel
    smtp:
      enabled: true
      from: ""
      password: ""
      port: 0
      provider: ""
      url: ""
      username: ""
    tracer:
      type: *tracerType
      enabled: *tracerEnabled
      app_name: *tracerAppName
      license_key: *tracerLicenseKey
      config_enabled: *tracerConfigEnabled
      distributed_tracer_enabled: *tracerDistributedTracingEnabled

  ingress:
    # -- Enable ingress for the worker
    enabled: false

  service:
    # -- Type of service for the worker
    type: ClusterIP
    # -- Port for the worker service
    port: 80

  autoscaling:
    # -- Enable autoscaling for the worker
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80


ingest:
  # @ignored
  image:
    # -- Repository to be used by the worker. Latest tag is used by default
    repository: *image
    # -- Pull policy for the worker image
    pullPolicy: IfNotPresent
    # @ignored
    tag: *tag

  ingress:
    # -- Enable ingress for the worker
    enabled: false

  env:
    interval: 60
    # @ignored
    log_level: *logLevel
    tracer:
      type: *tracerType
      enabled: *tracerEnabled
      app_name: *tracerAppName
      license_key: *tracerLicenseKey
      config_enabled: *tracerConfigEnabled
      distributed_tracer_enabled: *tracerDistributedTracingEnabled

  service:
    # -- Type of service for the worker
    type: ClusterIP
    # -- Port for the worker service
    port: 80

  autoscaling:
    # -- Enable autoscaling for the worker
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80


stream:
  # @ignored
  image:
    # -- Repository to be used by the stream. Latest tag is used by default
    repository: *image
    # -- Pull policy for the stream image
    pullPolicy: IfNotPresent
    # @ignored
    tag: *tag

  env:
    # @ignored
    tracer:
      type: *tracerType
      enabled: *tracerEnabled
      app_name: *tracerAppName
      license_key: *tracerLicenseKey
      config_enabled: *tracerConfigEnabled
      distributed_tracer_enabled: *tracerDistributedTracingEnabled

  ingress:
    # -- Enable ingress for the stream
    enabled: false

  service:
    # -- Type of service for the stream
    type: ClusterIP
    # -- Port for the stream service
    port: 80

  autoscaling:
    # -- Enable autoscaling for the stream
    enabled: false
    #    minReplicas: 1
    #    maxReplicas: 10
    #    targetCPUUtilizationPercentage: 80
    #    targetMemoryUtilizationPercentage: 80


server:
  # @ignored
  image:
    # -- Repository to be used by the server. Latest tag is used by default
    repository: *image
    # -- Pull policy for the server image
    pullPolicy: IfNotPresent
    # @ignored
    tag: *tag

  env:
    # @ignored
    log_level: *logLevel
    environment: "production"
    host: ""
    auth:
      jwt:
        enabled: true
      native:
        enabled: true
    search:
      enabled: false
      type: ""
      api_key: ""
      host: ""
    tracer:
      type: *tracerType
      enabled: *tracerEnabled
      app_name: *tracerAppName
      license_key: *tracerLicenseKey
      config_enabled: *tracerConfigEnabled
      distributed_tracer_enabled: *tracerDistributedTracingEnabled
    storage:
      enabled: false
      type: ""
      on_prem:
        path: ""
      s3:
        bucket: ""
        accessKey: ""
        secretKey: ""
        region: ""
        session_token: ""
        endpoint: ""

  ingress:
    # -- Enable ingress for the server
    enabled: false

  service:
    # -- Type of service for the server
    type: ClusterIP
    # -- Port for the server service
    port: 80

  autoscaling:
    # -- Enable autoscaling for the server
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80


scheduler:
  # @ignored
  image:
    # -- Repository to be used by the scheduler. Latest tag is used by default
    repository: *image
    # -- Pull policy for the scheduler image
    pullPolicy: IfNotPresent
    # @ignored
    tag: *tag


migrate:
  # @ignored
  image:
    # -- Repository to be used by to migrate. Latest tag is used by default. it will install before any other services.
    repository: *image
    # -- Pull policy for the migrate image
    pullPolicy: IfNotPresent
    # @ignored
    tag: *tag
