# Default values for convoy-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

app:
  replicaCount: 1
  port: 5005
  resources:
    limits:
      memory: 2000Mi
    requests:
      cpu: 1000m
      memory: 1000Mi
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "{{ .Values.app.port }}"

env:
  sign_up_enabled: false
  auth:
    jwt:
      enabled: true
    native:
      enabled: true
  log_level: "error"
  max_response_size: 50
  environment: ""
  host: ""
  tracer:
    enabled: false
    type: "otel"
    otel_sample_rate: 1.0
    otel_collector_url: ""
    otel_insecure_skip_verify: true
    otel_auth_header_name: ""
    otel_auth_header_value: ""
    sentry_dsn: ""
  storage:
    enabled: false
    type: ""
    on_prem:
      path: ""
    s3:
      bucket: ""
      accessKey: ""
      secretKey: ""
      region: ""
      session_token: ""
      endpoint: ""
extraEnvs: {}
# Examples:
  # ENV_NAME: value
  # HOST_IP:
  #  valueFrom:
  #    fieldRef:
  #      fieldPath: status.podIP
  # SECRET_ENV:
  #  valueFrom:
  #    secretKeyRef:
  #      name: thisissecretname
  #      key: thisissecretkey

image:
  repository: docker.cloudsmith.io/convoy/convoy/frain-dev/convoy
  pullPolicy: Always
  tag: v23.05.3

nameOverride: "convoy-server"
fullNameOverride: "convoy-server"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  ingressClassName: ""
  tls:
    - hosts:
        - test.com
      secretName: test-tls-secret
  hosts:
    - host: test.com
      http:
        paths:
          - path: /
            pathType: Prefix

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Pod disruption budget
podDisruptionBudget: {}
#  maxUnavailable: 1
#  minAvailable: 1

nodeSelector: {}
tolerations: []
affinity: {}
