# Default values for convoy-migrate.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

app:
  replicaCount: 1
  port: 3000
  # It's generally advisable not to set default resource limits,
  # allowing users to make intentional decisions based on their specific needs.
  # This approach also helps ensure that the chart can run in environments
  # with limited resources, like Minikube, KinD, etc. If you do wish to define resource limits,
  # uncomment the lines below, adjust them as needed, and remove the curly braces after 'resources:'.
  resources: {}
    # limits:
    #   cpu: 1000m
    #   memory: 2000Mi
    # requests:
    #   cpu: 1000m
    #   memory: 1000Mi

image:
  repository: docker.cloudsmith.io/convoy/convoy/frain-dev/convoy
  pullPolicy: Always
  tag: v23.05.3

nameOverride: "convoy-migrate"
fullNameOverride: "convoy-migrate"

ingress:
  enabled: false

nodeSelector: {}
tolerations: []
affinity: {}

jobAnnotations: {}
