# Default values for convoy-migrate.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

externalDatabase:
  enabled: false
nativeRedis:
  enabled: false
externalRedis:
  enabled: false

app:
  replicaCount: 1
  port: 3000
  resources:
    limits:
      memory: 60Mi
    requests:
      cpu: 40m
      memory: 50Mi

image:
  repository: docker.cloudsmith.io/convoy/convoy/frain-dev/convoy
  pullPolicy: Always
  tag: v23.05.3

nameOverride: "convoy-migrate"
fullNameOverride: "convoy-migrate"

ingress:
  enabled: false

nodeSelector: {}
tolerations: []
affinity: {}

jobAnnotations: {}
