apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "convoy-server.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "convoy-server.name" . }}
    helm.sh/chart: {{ include "convoy-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "convoy-server.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "80"
        updatedAt: {{ now | quote }}
      labels:
        app.kubernetes.io/name: {{ include "convoy-server.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:

      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          command: ["/cmd"]
          args: ["server"]
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
              protocol: TCP
          env:
            - name: SERVICE_NAME
              value: {{ .Chart.Name }}
            - name: PORT
              value: {{ .Values.app.port | quote }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
