# Default values for convoy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

app:
  replicaCount: 1
  port: 5008
  resources:
    limits:
      cpu: 50m
      memory: 60Mi
    requests:
      cpu: 40m
      memory: 50Mi

image:
  repository: docker.cloudsmith.io/convoy/convoy/frain-dev/convoy
  pullPolicy: Always
  tag: v0.9.2

nameOverride: "convoy-stream"
fullNameOverride: "convoy-stream"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
