apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "convoy-migrate.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "convoy-migrate.name" . }}
    helm.sh/chart: {{ include "convoy-migrate.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  backoffLimit: 10
  template:
    spec:
      volumes:
        - name: convoy-config
          configMap:
            name: convoy-config
            items: 
              - key: convoy.json
                path: convoy.json
      restartPolicy: OnFailure
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          volumeMounts:
            - name: convoy-config
              mountPath: /config
          command: ["/cmd"]
          args: ["migrate", "up", "--config", "/config/convoy.json"]
          resources:
            {{- toYaml .Values.app.resources | nindent 16 }}
