apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "convoy-worker.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "convoy-worker.name" . }}
    helm.sh/chart: {{ include "convoy-worker.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "convoy-worker.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "80"
        updatedAt: {{ now | quote }}
      labels:
        app.kubernetes.io/name: {{ include "convoy-worker.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      initContainers:
        - name: wait-for-migrate
          image: bitnami/kubectl:1.24.4
          command:
            - /bin/sh
            - -c
            - |
              until kubectl wait --for=condition=complete --timeout=600s job/convoy-migrate; do
                echo "Waiting for migrate job to complete..."
                sleep 5
              done
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/cmd"]
          args: ["worker"]
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
              protocol: TCP
          env:

            - name: SERVICE_NAME
              value: {{ .Chart.Name }}
            - name: PORT
              value: {{ .Values.app.port | quote }}

            {{- if .Values.global.externalDatabase.enabled }}
            - name: CONVOY_DB_SCHEME
              value: {{ .Values.global.externalDatabase.scheme | quote }}
            - name: CONVOY_DB_HOST
              value: {{ .Values.global.externalDatabase.host | quote }}
            - name: CONVOY_DB_PORT
              value: {{ .Values.global.externalDatabase.port | quote }}
            - name: CONVOY_DB_USERNAME
              value: {{ .Values.global.externalDatabase.username | quote }}
            - name: CONVOY_DB_PASSWORD
              value: {{ .Values.global.externalDatabase.password | quote }}
            - name: CONVOY_DB_DATABASE
              value: {{ .Values.global.externalDatabase.database | quote }}
            - name: CONVOY_DB_OPTIONS
              value: {{ .Values.global.externalDatabase.options | quote }}
            {{- end }}
            {{- if .Values.global.nativeRedis.enabled }}
            - name: CONVOY_REDIS_HOST
              value: {{ .Values.global.nativeRedis.host | quote }}
            - name: CONVOY_REDIS_PASSWORD
              value: {{ .Values.global.nativeRedis.password | quote }}
            - name: CONVOY_REDIS_PORT
              value: {{ .Values.global.nativeRedis.port | quote }}
            - name : CONVOY_REDIS_TYPE
              value: "NATIVE"
            {{- end }}
            {{- if .Values.global.externalRedis.enabled }}
            - name: CONVOY_REDIS_TYPE
              value: "EXTERNAL"
            - name: CONVOY_REDIS_HOST
              value: {{ .Values.global.externalRedis.host | quote }}
            - name: CONVOY_REDIS_PASSWORD
              value: {{ .Values.global.externalRedis.password | quote }}
            - name : CONVOY_REDIS_PORT
              value: {{ .Values.global.externalRedis.port | quote }}
            - name: CONVOY_REDIS_SCHEME
              value: {{ .Values.global.externalRedis.scheme | quote }}
            - name : CONVOY_REDIS_USERNAME
              value: {{ .Values.global.externalRedis.username | quote }}
            - name: CONVOY_REDIS_DATABASE
              value: {{ .Values.global.externalRedis.database | quote }}
            {{- end }}

          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
