apiVersion: v1
kind: Service
metadata:
  name: {{ include "convoy-worker.fullname" . }}
  labels: {{ include "convoy-worker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{ include "convoy-worker.selectorLabels" . | nindent 4 }}
